/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        text: {
          primary: '#111827',
          secondary: '#6b7280',
          tertiary: '#9ca3af',
          inverse: '#ffffff',
        },
        surface: {
          base: '#f9fafb',
          raised: '#ffffff',
          strong: '#ffffff',
          muted: '#f3f4f6',
          subtle: '#f9fafb',
        },
        border: {
          default: '#e5e7eb',
          subtle: 'rgba(0, 0, 0, 0.06)',
          strong: '#d1d5db',
          focus: '#111827',
        },
        accent: {
          primary: '#111827',
          dark: '#000000',
          blue: '#2563eb',
        },
        status: {
          positive: '#10b981',
          negative: '#ef4444',
          warning: '#f59e0b',
          info: '#3b82f6',
        },
      },
      spacing: {
        '1': '4px',
        '2': '6px',
        '3': '7.5px',
        '4': '8px',
        '5': '10px',
        '6': '12px',
        '7': '14px',
        '8': '15px',
        '9': '18px',
        '10': '20px',
        '12': '24px',
        '16': '32px',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '9999px',
      },
      fontSize: {
        xs: ['13.13px', { lineHeight: '18px' }],
        sm: ['13.5px', { lineHeight: '20px' }],
        md: ['14px', { lineHeight: '21px' }],
        base: ['15px', { lineHeight: '22.5px' }],
        lg: ['15px', { lineHeight: '22.5px' }],
        xl: ['16px', { lineHeight: '24px' }],
        '2xl': ['20px', { lineHeight: '28px' }],
        '3xl': ['24px', { lineHeight: '32px' }],
        '4xl': ['30px', { lineHeight: '38px' }],
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Open Sans',
          'Arial',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
        mono: ['SFMono-Regular', 'Roboto Mono', 'Menlo', 'monospace'],
      },
      boxShadow: {
        '1': 'inset 0px 0px 0px 1px rgba(0, 0, 0, 0.06), 0px 2px 8px rgba(0, 0, 0, 0.04)',
        card: 'inset 0px 0px 0px 1px rgba(0, 0, 0, 0.06), 0px 1px 3px rgba(0, 0, 0, 0.03)',
        floating: 'inset 0px 0px 0px 1px rgba(0, 0, 0, 0.08), 0px 8px 24px -4px rgba(0, 0, 0, 0.08)',
        button: '0px 1px 2px rgba(0, 0, 0, 0.05)',
      },
      transitionDuration: {
        instant: '100ms',
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
      },
      transitionTimingFunction: {
        'snappy-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
        standard: 'cubic-bezier(0.2, 0, 0, 1)',
      },
    },
  },
  plugins: [],
};
